routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('index','TestController');
Route::resource('user','UserController');
Route::resource('retailer','RetailerController');
Route::resource('customer','CustomerController');
Route::resource('visitor','VisitorController');

resources/views/layouts/header.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="" class="logo">
        <span class="logo-mini"><b>A</b>dmin</span>
        <span class="logo-lg"><b>Admin</b>Panel</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="" onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="hidden-xs">Logout</span>
                    </a>
                    <form id="logout-form" action="" method="POST" style="display: none;">
                        @csrf
                    </form>

                    <!--<ul class="dropdown-menu">
                        <li class="user-header">
                            <p>
                            <h2 style="color: white;">Admin Panel</h2>
                            </p>
                        </li>
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <form action="" method="post">
                                    @csrf
                                    <button type="submit" class="btn btn-default btn-flat">Sign out</button>
                                </form>
                            </div>
                        </li>
                    </ul>-->
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Admin | Demo</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.6 -->
        <link href="{{ asset("/admin-theme/bootstrap/css/bootstrap.min.css") }}" rel="stylesheet" type="text/css" />
        <!-- Font Awesome Icons -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <!-- Ionicons -->
        <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
        <link href="{{ asset("/admin-theme/dist/css/AdminLTE.min.css")}}" rel="stylesheet" type="text/css" />
        <link href="{{ asset("/admin-theme/dist/css/skins/skin-blue.min.css")}}" rel="stylesheet" type="text/css" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.9/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />
        <!--date Picker-->
        <link rel="stylesheet" href="{{asset('admin-theme/plugins/datepicker/datepicker3.css')}}">
        <link rel="stylesheet" href="{{ asset('backend/main.css') }}">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">

            @include('layouts.header')
            @include('layouts.sidebar')

            <div class="content-wrapper">
                @yield('content')
            </div>

            <!-- /.content-wrapper -->
            <footer class="main-footer">
                <!-- <strong>Copyright &copy;<a href="{{url('/')}}">XYZ</a>.</strong> All rights
                reserved. -->
            </footer>
            <!--Filtered Js-->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
            <script src=" https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js "></script>
            <!-- Bootstrap 3.3.2 JS -->
            <script src="{{ asset ("/admin-theme/bootstrap/js/bootstrap.min.js") }}" type="text/javascript"></script>
            <!-- AdminLTE App -->
            <script src="{{ asset ("/admin-theme/dist/js/app.min.js") }}" type="text/javascript"></script>
            <script src="https://cdn.ckeditor.com/4.8.0/standard/ckeditor.js" type="text/javascript"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-noty/2.3.7/packaged/jquery.noty.packaged.min.js"></script>
            <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.4.0/animate.min.css">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.9/js/fileinput.min.js"></script>
            <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.9/js/locales/LANG.js"></script>-->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
            <script src="{{asset('admin-theme/plugins/daterangepicker/daterangepicker.js')}}"></script>
             <!--datepicker--> 
            <script src="{{asset('admin-theme/plugins/datepicker/bootstrap-datepicker.js')}}"></script>
            <script src="{{asset('backend/main.js')}}"></script>

    </body>
</html>

resources/views/layouts/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li class="{{(App\Helper\Common::getCurrentController() == 'AdminController') ? 'active' : ''}}"><a href="{{route('index.index')}}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
            <li class="{{(App\Helper\Common::getCurrentController() == 'CompanyController') ? 'active' : ''}}"><a href="{{route('user.index')}}"><i class="fa fa-bars"></i> <span>Users</span></a></li>

            <li class="{{(App\Helper\Common::getCurrentController() == 'CompanyController') ? 'active' : ''}}"><a href="{{route('retailer.index')}}"><i class="fa fa-bars"></i> <span>Retailers</span></a></li>

            <li class="{{(App\Helper\Common::getCurrentController() == 'CompanyController') ? 'active' : ''}}"><a href="{{route('customer.index')}}"><i class="fa fa-bars"></i> <span>Customers</span></a></li>


            <li class="{{(App\Helper\Common::getCurrentController() == 'CompanyController') ? 'active' : ''}}"><a href="{{route('visitor.index')}}"><i class="fa fa-bars"></i> <span>Visitor</span></a></li>

            <li class="treeview">
                <!--          <a href="#">
                            <i class="fa fa-dashboard"></i> <span>Users</span>
                            <span class="pull-right-container">
                              <i class="fa fa-angle-left pull-right"></i>
                            </span>
                          </a>-->
                <ul class="treeview-menu">
                    {{-- <li class="active"><a href="index.html"><i class="fa fa-circle-o"></i>Admins</a></li> --}}

                </ul>
            </li>
            
            
            <li class="{{(Route::currentRouteName() == 'backend.password')? 'active' : '' }}"><a href=""><i class="fa fa-cog"></i><span>Change Password</span></a></li>
            <li class="{{(Route::currentRouteName() == 'settings.create')? 'active' : '' }}"><a href=""><i class="fa fa-cog"></i><span>Settings</span></a></li>

            <li class="{{(Route::currentRouteName() == 'countries.create')? 'active' : '' }}"><a href=""><i class="fa fa-cog"></i><span>Countries</span></a></li>
              
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>