routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('index','TestController');
Route::resource('user','UserController');
Route::resource('retailer','RetailerController');
Route::resource('customer','CustomerController');
Route::resource('visitor','VisitorController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'username', 'image'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\User;
use App\Repositories\UserRepository;
class UserController extends Controller
{
    


 protected $UserRepository;

    public function __construct(UserRepository $UserRepository) {
        $this->UserRepository = $UserRepository;
   
        
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = $this->UserRepository->index();
        return view('backend.user.index',compact('user'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('backend.user.create',compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, 
            ['name' => 'required',
              'username' => 'required',
              'email' => 'required',
              'password' => 'required'


        ]);


        $this->UserRepository->store($request);

        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = $this->UserRepository->find($id);
        return view('backend.user.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->UserRepository->find($id);
        return view('backend.user.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
         $this->UserRepository->update($request,$id);

        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $this->UserRepository->delete($id);
       return redirect()->route('user.index')->with('success','deleted');
    }
}

resources/views/backend/user/create.blade.php
@extends('layouts.master')
@section('content')


<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Add Users</h3>
               @if (session('status'))
				<p style="color: green;">{{session('status')}}</p>
			@endif
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" action="{{route('user.store')}}" method="post" enctype="multipart/form-data">
            	@csrf
              <div class="box-body">
              	<div class="row">
	              	<div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputEmail1">Name</label>
		                  <input type="text" name="name" class="form-control" placeholder="Enter Name">
		                  
		                  <div class="text-danger">{{ $errors->first('name') }}</div>
		                </div>
	                </div>

	                <div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputPassword1">Username</label>
		                  <input type="text" name="username" class="form-control" placeholder="Enter Username">
		                   <div class="text-danger">{{ $errors->first('username') }}</div>
		                </div>
		            </div>    
	            </div>

	            <div class="row">
	              	<div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputEmail1">Email</label>
		                  <input type="email" name="email" class="form-control" placeholder="Enter email">
		                   <div class="text-danger">{{ $errors->first('email') }}</div>
		                </div>
	                </div>

	                <div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputPassword1">Password</label>
		                  <input type="password" name="password" class="form-control" placeholder="Password">
		                   <div class="text-danger">{{ $errors->first('password') }}</div>
		                </div>
		        </div> 
	            </div>

	            <div class="row">
	              	
                        <div class="col-md-6">
		                <div class="form-group">
		                  <label for="profileImage">Select profile Image</label>
		                  <input type="file" name="profileImage" class="form-control" placeholder="Password">
		                   <div class="text-danger">{{ $errors->first('profileImage') }}</div>
		                </div>
		        </div> 
	            </div>

              </div>
              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{{route('user.index')}}"><button type="button" class="btn btn-danger">Cancel</button>
              </div>
          </form>
		</div>
	</div>
</section>
@endsection

resources/views/backend/user/edit.blade.php
@extends('layouts.master')
@section('content')

@php 
use App\Model\User; 
@endphp

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Edit User</h3>
                   
                </div>
                <!-- /.box-header -->
                <!-- form start -->


                <form role="form" action="{{route('user.update',$user->id)}}" method="post" enctype="multipart/form-data">
                            <input type="hidden" name="_method" value="PUT">


                    @csrf
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Name</label>
                                    <input type="text" name="name" class="form-control" value="{{$user->name}}">
                                    <div class="text-danger">{{ $errors->first('name') }}</div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Username</label>
                                    <input type="text" name="username" class="form-control" value="{{$user->username}}">
                                    <div class="text-danger">{{ $errors->first('username') }}</div>
                                </div>
                            </div>    
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Email</label>
                                    <input type="email" name="email" class="form-control" value="{{$user->email}}">
                                    <div class="text-danger">{{ $errors->first('email') }}</div>
                                </div>
                            </div>

                         
                                        </div>
                                    </div>
                                   
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        
                        
                        
                        
                        
                    </div>
                </form>
            </div>
        </div>
</section>
@endsection

resources/views/backend/user/index.blade.php
@extends('layouts.master')
@section('content')
<!-- /.row -->
<section class="content">
		<p class="pull-right">
			<a href="{{route('user.create')}}" class="btn btn-sm btn-success">Add Company</a>
	  	</p>
      <div class="row">
        <div class="col-xs-12">
          <div class="box box-primary">
            <div class="box-header">
              <h3 class="box-title">Companies</h3>
              <div class="box-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">
                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive">
           
              <table class="table table-hover table-bordered">
                <tr>
                  <th>Sr.No.</th>
                  <th>Name</th>
                  <th>User Name</th>
                  <th>Email</th>
                 
                  
                  <th>Action</th>
                </tr>
               @foreach($user as $us)
               
                <tr>
                  <td>{{$us->id}}</td>
                  <td>{{$us->name}}</td>
                  <td>{{$us->username}}</td>
                  <td>{{$us->email}}</td>
                  
                  <td>
                  	<label class="switch">
          					  <input type="checkbox" class="update-status"  data-id="" data-url="" >
          					  <span class="slider round"></span>
          					</label>
                  </td>
                    
                  <td> 
                    <form action="{{route('user.destroy',$us->id)}}" method="post" role="form">
                      @csrf

                  			<a href="{{route('user.show',$us->id)}}"><button type="button" title="view" class="btn btn-success btn-xs"><span class="glyphicon glyphicon-eye-open"></span></button></a>

                            <a href="{{route('user.edit',$us->id)}}"><button type="button" title="edit" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-edit"></span></button></a>
                              <input type="hidden" name="_method" value="DELETE"> 
                            <button  title="Delete" type="submit" class="btn btn-danger btn-xs" onclick="return confirm('Are you sure you want to delete this user?');"><span class="glyphicon glyphicon-trash"></span></button>
                  </td></form>
                </tr>
                @endforeach
               
              </table>
             
	            <div><h2></h2></div>
	          
            </div>

            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>
      </section>
      @endsection

resources/views/backend/user/show.blade.php
@extends('layouts.master')
@section('content')

@php 
use App\Model\User; 
@endphp

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">User Details</h3>
                    @if (session('status'))
                    <p style="color: green;">{{session('status')}}</p>
                    @endif
                </div>
                <!-- /.box-header -->
                <!-- form start -->

                <form role="form">
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Name :</label>
                                    {{$user->name}}
                                    <!-- dd($user); -->
                                    <div class="text-danger">{{ $errors->first('name') }}</div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Username :</label>
                                    {{$user->username}}
                                    <div class="text-danger">{{ $errors->first('username') }}</div>
                                </div>
                            </div>    
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Email :</label>
                                    {{$user->email}}
                                    <div class="text-danger">{{ $errors->first('email') }}</div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                
                                <div class="text-danger">{{ $errors->first('role') }}</div>
                            </div> 
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Status :</label>
                                    {{($user->status == 1)? 'Enable' : 'Disable'}}
                                    <div class="text-danger">{{ $errors->first('email') }}</div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label for="exampleInputEmail1">Profile Image :</label>
                                <p><img src="{{(isset($user->profileImage))? asset('/uploads/profilepics/'.$user->profileImage) : asset('uploads/no_image.png')}}" height="120px" width="120px;" alt="profileImage"></p>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        
                    </div>
                </form>
            </div>
        </div>
</section>
@endsection